# Generated by Django 4.0b1 on 2021-11-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remember',
            field=models.TextField(default=''),
        ),
    ]
