# Generated by Django 4.0b1 on 2021-11-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_remember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='remember',
        ),
    ]
