# Generated by Django 4.0rc1 on 2021-11-22 10:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_editorjs.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_user_remember'),
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Remember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('1W', '1Week'), ('2W', '2Week'), ('1M', '1Month'), ('3M', '3Months'), ('6M', '6Months'), ('1Y', '1Year'), ('2Y', '2Years')], default='1W', max_length=2)),
                ('showing_date', models.DateField(verbose_name=datetime.datetime(2021, 11, 29, 10, 2, 23, 143056))),
                ('remember', django_editorjs.fields.EditorJsField()),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remembers', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
