# Generated by Django 4.0b1 on 2021-11-19 09:09

from django.db import migrations, models
import django.db.models.deletion
import django_editorjs.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_user_remember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('remember', django_editorjs.fields.EditorJsField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remembers', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
