# Generated by Django 3.2 on 2021-12-14 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remembers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remember',
            name='showing_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 0, 51, 15, 186717), verbose_name='Showing Date'),
        ),
    ]
