# Generated by Django 4.0rc1 on 2021-12-01 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remembers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remember',
            name='showing_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 8, 0, 27, 14, 109186), verbose_name='Showing Date'),
        ),
    ]
