# Generated by Django 4.0b1 on 2021-11-19 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remembers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(max_length=80)),
                ('remember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='remembers.remember')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
