# Generated by Django 3.2 on 2021-12-14 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remembers', '0002_alter_remember_showing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remember',
            name='showing_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 0, 51, 34, 550217), verbose_name='Showing Date'),
        ),
        migrations.AlterField(
            model_name='remember',
            name='stage',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'),)), ('Video', (('vhs', 'VHS Tape'),)), ('unknown', 'Unknown')], default='Audio', max_length=10),
        ),
    ]
