# Generated by Django 3.2 on 2021-12-14 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remembers', '0003_auto_20211214_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remember',
            name='showing_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 0, 57, 22, 580726), verbose_name='Showing Date'),
        ),
        migrations.AlterField(
            model_name='remember',
            name='stage',
            field=models.CharField(choices=[('1W', (('1 Week', '7'),)), ('2W', (('2 Week', '7'),)), ('1M', (('1 Month', '7'),)), ('2W', (('2 Month', '7'),))], default='1W', max_length=10),
        ),
    ]
