# Generated by Django 4.0rc1 on 2021-11-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remembers', '0004_stage_remember_shirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remember',
            name='shirt_size',
        ),
        migrations.AddField(
            model_name='remember',
            name='stage',
            field=models.CharField(choices=[('1W', '1Week'), ('2W', '2Week'), ('1M', '1Month'), ('3M', '3Months'), ('6M', '6Months'), ('1Y', '1Year'), ('2Y', '2Years')], default='1W', max_length=2),
        ),
    ]
