# Generated by Django 3.2 on 2021-12-14 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remembers', '0010_auto_20211214_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remember',
            name='showing_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 20, 44, 7, 661465), verbose_name='Showing Date'),
        ),
        migrations.AlterField(
            model_name='remember',
            name='stage',
            field=models.CharField(choices=[(7, '1 Week'), (14, '2 Week'), (30, '1 Month'), (30, '2 Month'), (60, '3 Month'), (180, '6 Month'), (360, '1 Year')], default=[(7, '1 Week'), (14, '2 Week'), (30, '1 Month'), (30, '2 Month'), (60, '3 Month'), (180, '6 Month'), (360, '1 Year')], max_length=7),
        ),
    ]
