# Generated by Django 3.2 on 2021-12-15 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remembers', '0012_auto_20211214_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remember',
            name='slug',
        ),
        migrations.AlterField(
            model_name='remember',
            name='showing_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 22, 0, 17, 5, 2499), verbose_name='Showing Date'),
        ),
        migrations.AlterField(
            model_name='remember',
            name='stage',
            field=models.CharField(choices=[('7', '1 Week'), ('14', '2 Week'), ('30', '1 Month'), ('60', '2 Month'), ('90', '3 Month'), ('180', '6 Month'), ('360', '1 Year')], default='7', max_length=7),
        ),
    ]
